- import_tasks: "{{ role_path }}/tasks/validate_config.yml"
  when: "run_setup|bool and matrix_coturn_enabled|bool"
  tags:
    - setup-all
    - setup-coturn

- import_tasks: "{{ role_path }}/tasks/setup_coturn.yml"
  when: run_setup|bool
  tags:
    - setup-all
    - setup-coturn
